package org.terracotta.utils.domain;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.terracotta.utils.RandomUtil;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

public class Customer implements Serializable {
    public static final List<String> listFirstName = new ArrayList<String>();
    public static final List<String> listLastName = new ArrayList<String>();
    public static final List<String> listOccupations = new ArrayList<String>();
    static {
        listLastName.add("Smith");
        listLastName.add("Baker");
        listLastName.add("Finley");
        listLastName.add("Hunter");
        listLastName.add("Furter");
        listLastName.add("Carlson");
        listLastName.add("Beaks");
        listLastName.add("Jones");
        listLastName.add("Hathaway");
        listLastName.add("Lawson");
        listLastName.add("Night");
        listLastName.add("Yunts");
        listLastName.add("Jenks");
        listLastName.add("Williams");
        listLastName.add("Potter");
        listLastName.add("Henry");
        listLastName.add("McKenny");
        listLastName.add("Woods");
        listLastName.add("Milborne");
        listLastName.add("Winkler");
        listLastName.add("Katz");
        listLastName.add("Wilkinson");
        listLastName.add("Barns");
        listLastName.add("Cobra");

        listFirstName.add("Joe");
        listFirstName.add("Sally");
        listFirstName.add("Sara");
        listFirstName.add("Holly");
        listFirstName.add("Frank");
        listFirstName.add("George");
        listFirstName.add("Henry");
        listFirstName.add("Eric");
        listFirstName.add("Tracey");
        listFirstName.add("Kyle");
        listFirstName.add("Hailey");
        listFirstName.add("Sue");
        listFirstName.add("Dan");

        listOccupations.add("Able Seamen");
        listOccupations.add("Account Collector");
        listOccupations.add("Accounting Specialist");
        listOccupations.add("Adjustment Clerk");
        listOccupations.add("Administrative Assistant");
        listOccupations.add("Administrative Law Judge");
        listOccupations.add("Administrative Service Manager");
        listOccupations.add("Admiralty Lawyer");
        listOccupations.add("Adult Literacy and Remedial Education Teachers");
        listOccupations.add("Advertising Account Executive");
        listOccupations.add("Advertising Agency Coordinator");
        listOccupations.add("Aeronautical & Aerospace Engineer");
        listOccupations.add("Aerospace Engineering Technician");
        listOccupations.add("Agricultural Crop Farm Manager");
        listOccupations.add("Agricultural Engineer");
        listOccupations.add("Agricultural Equipment Operator");
        listOccupations.add("Agricultural Inspector");
        listOccupations.add("Agricultural Product Sorter");
        listOccupations.add("Agricultural Sciences Professor");
        listOccupations.add("Agricultural Technician");
        listOccupations.add("Air Crew Member");
        listOccupations.add("Air Crew Officer");
        listOccupations.add("Air Traffic Controller");
        listOccupations.add("Aircraft Assembler");
        listOccupations.add("Aircraft Body and Bonded Structure Repairer");
        listOccupations.add("Aircraft Cargo Handling Supervisor");
        listOccupations.add("Aircraft Examiner");
        listOccupations.add("Aircraft Launch and Recovery Officer");
        listOccupations.add("Aircraft Launch and Recovery Specialist");
        listOccupations.add("Aircraft Mechanic");
        listOccupations.add("Airfield Operations Specialist");
        listOccupations.add("Airline Flight Attendant");
        listOccupations.add("Airline Flight Control Administrator");
        listOccupations.add("Airline Flight Operations Administrator");
        listOccupations.add("Airline Flight Reservations Administrator");
        listOccupations.add("Airport Administrator");
        listOccupations.add("Airport Design Engineer");
        listOccupations.add("Alcohol & Drug Abuse Assistance Coordinator");
        listOccupations.add("Alumni Relations Coordinator");
        listOccupations.add("Ambulance Drivers");
        listOccupations.add("Amusement Park & Recreation Attendants");
        listOccupations.add("Anesthesiologist (MD)");
        listOccupations.add("Animal Breeder");
        listOccupations.add("Animal Control Worker");
        listOccupations.add("Animal Husbandry Worker Supervisor");
        listOccupations.add("Animal Keepers and Groomers");
        listOccupations.add("Animal Kennel Supervisor");
        listOccupations.add("Animal Scientist");
        listOccupations.add("Animal Trainer");
        listOccupations.add("Animation Cartoonist");
        listOccupations.add("Answering Service Operator");
        listOccupations.add("Anthropology and Archeology Professor");
        listOccupations.add("Anti-Terrorism Intelligence Agent");
        listOccupations.add("Appeals Referee");
        listOccupations.add("Aquaculturist (Fish Farmer)");
        listOccupations.add("Aquarium Curator");
        listOccupations.add("Architecture Professor");
        listOccupations.add("Area, Ethnic, and Cultural Studies Professor");
        listOccupations.add("Armored Assault Vehicle Crew Member");
        listOccupations.add("Armored Assault Vehicle Officer");
        listOccupations.add("Art Appraiser");
        listOccupations.add("Art Director");
        listOccupations.add("Art Restorer");
        listOccupations.add("Art Therapist");
        listOccupations.add("Art, Drama, and Music Professor");
        listOccupations.add("Artillery and Missile Crew Member");
        listOccupations.add("Artillery and Missile Officer");
        listOccupations.add("Artists Agent (Manager)");
        listOccupations.add("Athletes' Business Manager");
        listOccupations.add("Athletic Coach");
        listOccupations.add("Athletic Director");
        listOccupations.add("Athletic Trainer");
        listOccupations.add("ATM Machine Servicer");
        listOccupations.add("Atmospheric and Space Scientist");
        listOccupations.add("Audio-Visual Collections Specialist");
        listOccupations.add("Audiovisual Production Specialist");
        listOccupations.add("Automobile Mechanic");
        listOccupations.add("Automotive Body Repairer");
        listOccupations.add("Automotive Engineer");
        listOccupations.add("Automotive Glass Installer");
        listOccupations.add("Avionics Technician");
        listOccupations.add("Baggage Porters and Bellhops");
        listOccupations.add("Baker (Commercial)");
        listOccupations.add("Ballistics Expert");
        listOccupations.add("Bank and Branch Managers");
        listOccupations.add("Bank Examiner");
        listOccupations.add("Bank Teller");
        listOccupations.add("Benefits Manager");
        listOccupations.add("Bicycle Mechanic");
        listOccupations.add("Billing Specialist");
        listOccupations.add("Bindery Machine Set-Up Operators");
        listOccupations.add("Bindery Machine Tender");
        listOccupations.add("Biological Technician");
        listOccupations.add("Biology Professor");
        listOccupations.add("Biomedical Engineer");
        listOccupations.add("Biomedical Equipment Technician");
        listOccupations.add("Boat Builder");
        listOccupations.add("Book Editor");
        listOccupations.add("Border Patrol Agent");
        listOccupations.add("Brattice Builder");
        listOccupations.add("Bridge and Lock Tenders");
        listOccupations.add("Broadcast News Analyst");
        listOccupations.add("Broadcast Technician");
        listOccupations.add("Broker's Floor Representative");
        listOccupations.add("Brokerage Clerk");
        listOccupations.add("Budget Accountant");
        listOccupations.add("Budget Analyst");
        listOccupations.add("Building Inspector");
        listOccupations.add("Building Maintenance Mechanic");
        listOccupations.add("Bulldozer / Grader Operator");
        listOccupations.add("Bus and Truck Mechanics");
        listOccupations.add("Bus Boy / Bus Girl");
        listOccupations.add("Bus Driver (School)");
        listOccupations.add("Bus Driver (Transit)");
        listOccupations.add("Business Professor");
        listOccupations.add("Business Service Specialist");
        listOccupations.add("Cabinet Maker");
        listOccupations.add("Camp Director");
        listOccupations.add("Caption Writer");
        listOccupations.add("Cardiologist (MD)");
        listOccupations.add("Cardiopulmonary Technologist");
        listOccupations.add("Career Counselor");
        listOccupations.add("Cargo and Freight Agents");
        listOccupations.add("Carpenter's Assistant");
        listOccupations.add("Carpet Installer");
        listOccupations.add("Cartographer (Map Scientist)");
        listOccupations.add("Cartographic Technician");
        listOccupations.add("Cartoonist (Publications)");
        listOccupations.add("Casino Cage Worker");
        listOccupations.add("Casino Cashier");
        listOccupations.add("Casino Dealer");
        listOccupations.add("Casino Floor Person");
        listOccupations.add("Casino Manager");
        listOccupations.add("Casino Pit Boss");
        listOccupations.add("Casino Slot Machine Mechanic");
        listOccupations.add("Casino Surveillance Officer");
        listOccupations.add("Casting Director");
        listOccupations.add("Catering Administrator");
        listOccupations.add("Ceiling Tile Installer");
        listOccupations.add("Cement Mason");
        listOccupations.add("Ceramic Engineer");
        listOccupations.add("Certified Public Accountant (CPA)");
        listOccupations.add("Chaplain (Prison, Military, Hospital)");
        listOccupations.add("Chemical Engineer");
        listOccupations.add("Chemical Equipment Operator");
        listOccupations.add("Chemical Plant Operator");
        listOccupations.add("Chemical Technicians");
        listOccupations.add("Chemistry Professor");
        listOccupations.add("Chief Financial Officer");
        listOccupations.add("Child Care Center Administrator");
        listOccupations.add("Child Care Worker");
        listOccupations.add("Child Life Specialist");
        listOccupations.add("Child Support Investigator");
        listOccupations.add("Child Support Services Worker");
        listOccupations.add("City Planning Aide");
        listOccupations.add("Civil Drafter");
        listOccupations.add("Civil Engineer");
        listOccupations.add("Civil Engineering Technician");
        listOccupations.add("Clergy Member (Religious Leader)");
        listOccupations.add("Clinical Dietitian");
        listOccupations.add("Clinical Psychologist");
        listOccupations.add("Clinical Sociologist");
        listOccupations.add("Coatroom and Dressing Room Attendants");
        listOccupations.add("College/University Professor");
        listOccupations.add("Commercial Designer");
        listOccupations.add("Commercial Diver");
        listOccupations.add("Commercial Fisherman");
        listOccupations.add("Communication Equipment Mechanic");
        listOccupations.add("Communications Professor");
        listOccupations.add("Community Health Nurse");
        listOccupations.add("Community Organization Worker");
        listOccupations.add("Community Welfare Worker");
        listOccupations.add("Compensation Administrator");
        listOccupations.add("Compensation Specialist");
        listOccupations.add("Compliance Officer");
        listOccupations.add("Computer Aided Design (CAD) Technician");
        listOccupations.add("Computer and Information Scientists, Research");
        listOccupations.add("Computer and Information Systems Managers");
        listOccupations.add("Computer Applications Engineer");
        listOccupations.add("Computer Controlled Machine Tool Operators");
        listOccupations.add("Computer Customer Support Specialist");
        listOccupations.add("Computer Hardware Technician");
        listOccupations.add("Computer Operators");
        listOccupations.add("Computer Programmer");
        listOccupations.add("Computer Science Professor");
        listOccupations.add("Computer Security Specialist");
        listOccupations.add("Computer Software Engineers");
        listOccupations.add("Computer Software Technician");
        listOccupations.add("Computer Systems Engineer");
        listOccupations.add("Congressional Aide");
        listOccupations.add("Conservation Scientist");
        listOccupations.add("Construction Driller");
        listOccupations.add("Construction Laborer");
        listOccupations.add("Construction Manager");
        listOccupations.add("Construction Trades Supervisor");
        listOccupations.add("Contract Administrator");
        listOccupations.add("Contract Specialist");
        listOccupations.add("Control Center Specialist (Military)");
        listOccupations.add("Controller (Finance)");
        listOccupations.add("Cook (Cafeteria)");
        listOccupations.add("Cook (Fast Food)");
        listOccupations.add("Cook (Private Household)");
        listOccupations.add("Cook (Restaurant)");
        listOccupations.add("Cook (Short Order)");
        listOccupations.add("Copy Writer");
        listOccupations.add("Corporation Lawyer");
        listOccupations.add("Correction Officer");
        listOccupations.add("Correspondence Clerk");
        listOccupations.add("Cosmetologist (Hair Stylist)");
        listOccupations.add("Cost Accountant");
        listOccupations.add("Cost Analysis Engineer");
        listOccupations.add("Cost Estimator");
        listOccupations.add("Costume Attendant");
        listOccupations.add("Counseling Psychologist");
        listOccupations.add("Counter and Rental Clerks");
        listOccupations.add("County or City Auditor");
        listOccupations.add("Couriers and Messengers");
        listOccupations.add("Court Administrator");
        listOccupations.add("Court Clerk");
        listOccupations.add("Court Reporter");
        listOccupations.add("Craft Artist");
        listOccupations.add("Crane Operator");
        listOccupations.add("Credit Adjuster");
        listOccupations.add("Credit Analyst");
        listOccupations.add("Credit Reporter");
        listOccupations.add("Criminal Investigator (Detective)");
        listOccupations.add("Criminal Justice Professor");
        listOccupations.add("Criminal Lawyer");
        listOccupations.add("Crop Workers Supervisor");
        listOccupations.add("Crossing Guard");
        listOccupations.add("Custom Tailor");
        listOccupations.add("Customer Service Representative (Utilities)");
        listOccupations.add("Customer Service Supervisor");
        listOccupations.add("Customs Inspector");
        listOccupations.add("Cutting Machine Operators");
        listOccupations.add("Dairy Technologist");
        listOccupations.add("Database Administrator");
        listOccupations.add("Deaf Students Teacher");
        listOccupations.add("Delivery Driver");
        listOccupations.add("Demonstrators and Product Promoters");
        listOccupations.add("Dental / Orthodontic Office Administrator");
        listOccupations.add("Dental Assistant");
        listOccupations.add("Dental Hygienist");
        listOccupations.add("Dental Laboratory Technician");
        listOccupations.add("Dentist (MD)");
        listOccupations.add("Dermatologist (MD)");
        listOccupations.add("Desktop Publishing Specialist");
        listOccupations.add("Developmental Psychologist");
        listOccupations.add("Die Cutter Operator");
        listOccupations.add("Dietetic Technician");
        listOccupations.add("Dietitian and Nutritionist");
        listOccupations.add("Directory Assistance Operator");
        listOccupations.add("Disabled Students Teacher");
        listOccupations.add("Disk Jockey");
        listOccupations.add("Dispatcher (Safety Vehicles)");
        listOccupations.add("Door To Door Salesmen");
        listOccupations.add("Dry Wall Installer");
        listOccupations.add("Economics Professor");
        listOccupations.add("Editorial Writer, Newspapers & Magazines");
        listOccupations.add("Education and Training Administrator");
        listOccupations.add("Education Professor");
        listOccupations.add("Educational Administrator");
        listOccupations.add("Educational Psychologist");
        listOccupations.add("Educational Resource Coordinator");
        listOccupations.add("Educational Therapist");
        listOccupations.add("EEG Technician/Technologist");
        listOccupations.add("Electric Meter Installer");
        listOccupations.add("Electric Motor Mechanic");
        listOccupations.add("Electrical and Electronic Inspector");
        listOccupations.add("Electrical Drafter");
        listOccupations.add("Electrical Engineers");
        listOccupations.add("Electrical Parts Reconditioner");
        listOccupations.add("Electrical Technician");
        listOccupations.add("Electro-Mechanical Technicians");
        listOccupations.add("Electromechanical Equipment Assembler");
        listOccupations.add("Electronic Drafter");
        listOccupations.add("Electronics Engineer");
        listOccupations.add("Electronics Technician");
        listOccupations.add("Elementary School Administrator");
        listOccupations.add("Elementary School Teacher");
        listOccupations.add("Elevator Mechanic");
        listOccupations.add("Emergency Management Specialist");
        listOccupations.add("Emergency Medical Technician");
        listOccupations.add("Employee Benefits Analyst");
        listOccupations.add("Employee Training Instructor");
        listOccupations.add("Employment Administrator");
        listOccupations.add("Employment and Placement Specialist");
        listOccupations.add("Employment Interviewer");
        listOccupations.add("Engine and Machine Assemblers");
        listOccupations.add("Engineering Managers");
        listOccupations.add("Engineering Professor");
        listOccupations.add("English Language and Literature Professor");
        listOccupations.add("Environmental Compliance Inspector");
        listOccupations.add("Environmental Disease Analyst");
        listOccupations.add("Environmental Engineer");
        listOccupations.add("Environmental Planner");
        listOccupations.add("Environmental Research Analyst");
        listOccupations.add("Environmental Science Technician");
        listOccupations.add("Environmental Science Professsor");
        listOccupations.add("Environmental Technician");
        listOccupations.add("Equal Opportunity Representative");
        listOccupations.add("Etchers and Engravers");
        listOccupations.add("Excavating Machine Operator");
        listOccupations.add("Excavating Supervisor");
        listOccupations.add("Executive Secretary");
        listOccupations.add("Exercise Physiologist");
        listOccupations.add("Exhibit Artist");
        listOccupations.add("Exhibit Designer");
        listOccupations.add("Experimental Psychologist");
        listOccupations.add("Explosives Worker");
        listOccupations.add("Export Agent");
        listOccupations.add("Fabric and Apparel Patternmakers");
        listOccupations.add("Facilities Planner");
        listOccupations.add("Factory Layout Engineer");
        listOccupations.add("Family Caseworker");
        listOccupations.add("Family Practitioner (MD)");
        listOccupations.add("Farm Equipment Mechanic");
        listOccupations.add("Farm Hand");
        listOccupations.add("Farm Labor Contractor");
        listOccupations.add("Farm Manager");
        listOccupations.add("Farm Products Purchasing Agent");
        listOccupations.add("Farmers and Ranchers");
        listOccupations.add("Fashion Artist");
        listOccupations.add("Fashion Coordinator");
        listOccupations.add("Fashion Designer");
        listOccupations.add("Fashion Model");
        listOccupations.add("Fence Installer");
        listOccupations.add("Field Contractor");
        listOccupations.add("Field Health Officer");
        listOccupations.add("File Clerk");
        listOccupations.add("Film Editor");
        listOccupations.add("Film Laboratory Technician");
        listOccupations.add("Finance Manager");
        listOccupations.add("Financial Aid Counselor");
        listOccupations.add("Financial Analyst");
        listOccupations.add("Financial Examiner");
        listOccupations.add("Financial Planner");
        listOccupations.add("Financial Services Sales Agent");
        listOccupations.add("Fine Artist");
        listOccupations.add("Fire Inspector");
        listOccupations.add("Fire Investigator");
        listOccupations.add("Fire Prevention Engineer");
        listOccupations.add("Fire Protection Engineer");
        listOccupations.add("Fire Protection Engineering Technician");
        listOccupations.add("Fish & Game Warden");
        listOccupations.add("Fish Hatchery Specialist");
        listOccupations.add("Fishery Worker Supervisor");
        listOccupations.add("Fitness Trainer");
        listOccupations.add("Flight Engineers");
        listOccupations.add("Floral Designer");
        listOccupations.add("Food & Drug Inspector");
        listOccupations.add("Food Batchmaker");
        listOccupations.add("Food Preparation Worker");
        listOccupations.add("Food Science Technicians");
        listOccupations.add("Food Technologist");
        listOccupations.add("Foreign Exchange Trader");
        listOccupations.add("Foreign Language Interpreter");
        listOccupations.add("Foreign Language Teacher");
        listOccupations.add("Foreign Language Translator");
        listOccupations.add("Foreign Service Officer");
        listOccupations.add("Foreign Service Peacekeeping Specialist");
        listOccupations.add("Foreign Student Adviser");
        listOccupations.add("Forensic Science Technicians");
        listOccupations.add("Forensics Psychologist");
        listOccupations.add("Forest and Conservation Technician");
        listOccupations.add("Forest Engineer");
        listOccupations.add("Forest Fire Prevention Supervisor");
        listOccupations.add("Forest Fire Inspector");
        listOccupations.add("Forestry and Conservation Professor");
        listOccupations.add("Forging Machine Operator");
        listOccupations.add("Forklift and Industrial Truck Operators");
        listOccupations.add("Fraud Investigator");
        listOccupations.add("Freight and Stock Handler");
        listOccupations.add("Fund Raiser");
        listOccupations.add("Funds Development Administrator");
        listOccupations.add("Funeral Attendant");
        listOccupations.add("Funeral Director");
        listOccupations.add("Furniture Designer");
        listOccupations.add("Furniture Finishers");
        listOccupations.add("Game Runner");
        listOccupations.add("Gas Plant Operator");
        listOccupations.add("General and Operations Managers");
        listOccupations.add("General Farmworkers");
        listOccupations.add("General Internists (MD)");
        listOccupations.add("Geography Professor");
        listOccupations.add("Geological Data Technicians");
        listOccupations.add("Geological Technician (Drafter)");
        listOccupations.add("Glass Blower");
        listOccupations.add("Gluing Machine Operators");
        listOccupations.add("Golf Course Superintendent");
        listOccupations.add("Government Budget Analyst");
        listOccupations.add("Government Property Inspectors");
        listOccupations.add("Government Service Executives");
        listOccupations.add("Graduate Teaching Assistant");
        listOccupations.add("Graphic Designer");
        listOccupations.add("Greenhouse and Nursery Manager");
        listOccupations.add("Gynecologist (MD)");
        listOccupations.add("Hand and Portable Tool Mechanic");
        listOccupations.add("Hand Sewer");
        listOccupations.add("Harbor Master");
        listOccupations.add("Harbor, Lake & Waterways Police");
        listOccupations.add("Hardwood Floor Finisher");
        listOccupations.add("Hazardous Materials Removal Worker");
        listOccupations.add("Hazardous Waste Management Analyst");
        listOccupations.add("Health Care Facilities Inspector");
        listOccupations.add("Health Case Manager");
        listOccupations.add("Health Educators");
        listOccupations.add("Health Psychologist");
        listOccupations.add("Hearing Officer");
        listOccupations.add("Heating, A/C, Refrigeration Technician");
        listOccupations.add("Heavy Equipment Mechanic");
        listOccupations.add("High School Administrator");
        listOccupations.add("High School Guidance Counselor");
        listOccupations.add("High School Teacher");
        listOccupations.add("Highway Maintenance Worker");
        listOccupations.add("Highway Patrol Pilot");
        listOccupations.add("Historic Site Administrator");
        listOccupations.add("Historical Archivist");
        listOccupations.add("History Professor");
        listOccupations.add("Home Appliance Installer");
        listOccupations.add("Home Appliance Repairer");
        listOccupations.add("Home Economics Teacher");
        listOccupations.add("Home Economist");
        listOccupations.add("Home Entertainment System Installer");
        listOccupations.add("Home Health Aide");
        listOccupations.add("Home Health Technician");
        listOccupations.add("Horticultural Worker Supervisor");
        listOccupations.add("Horticulture Therapist");
        listOccupations.add("Horticulturist (Vineyard)");
        listOccupations.add("Hospital Administrator");
        listOccupations.add("Hospital Nurse");
        listOccupations.add("Hosts and Hostesses");
        listOccupations.add("Hotel and Motel Desk Clerks");
        listOccupations.add("Hotel Convention/Events Coordinator");
        listOccupations.add("Hotel Manager");
        listOccupations.add("Housekeeping Supervisors");
        listOccupations.add("Human Factors Psychologist");
        listOccupations.add("Human Resources Management Advisor");
        listOccupations.add("Human Resources Management Consultant");
        listOccupations.add("Hydraulic Engineer");
        listOccupations.add("Immigration Inspector");
        listOccupations.add("Industrial Air Pollution Analyst");
        listOccupations.add("Industrial Arts Teacher");
        listOccupations.add("Industrial Designer");
        listOccupations.add("Industrial Engineer");
        listOccupations.add("Industrial Engineering Technician");
        listOccupations.add("Industrial Health Engineer");
        listOccupations.add("Industrial Hygienist");
        listOccupations.add("Industrial Machinery Mechanics");
        listOccupations.add("Industrial Relations Analyst");
        listOccupations.add("Industrial Relations Specialist");
        listOccupations.add("Industrial Therapist");
        listOccupations.add("Industrial Waste Inspector");
        listOccupations.add("Industrial-Organizational Psychologist");
        listOccupations.add("Infantry Officers");
        listOccupations.add("Instructional Coordinators");
        listOccupations.add("Instructor, Police-Canine Services");
        listOccupations.add("Instrument Technician");
        listOccupations.add("Insulation Installer");
        listOccupations.add("Insurance Adjuster");
        listOccupations.add("Insurance Agent");
        listOccupations.add("Insurance Appraiser (Auto Damage)");
        listOccupations.add("Insurance Claim Examiner");
        listOccupations.add("Insurance Claims Adjuster");
        listOccupations.add("Insurance Claims Clerks");
        listOccupations.add("Insurance Estate Planner");
        listOccupations.add("Insurance Lawyer");
        listOccupations.add("Insurance Policy Processing Clerk");
        listOccupations.add("Insurance Underwriter");
        listOccupations.add("Intelligence Specialist (Government)");
        listOccupations.add("Interior Designer");
        listOccupations.add("Internal Auditor");
        listOccupations.add("Interpreter for the Hearing Impaired");
        listOccupations.add("Irradiated-Fuel Handlers");
        listOccupations.add("Irrigation Engineer");
        listOccupations.add("IT Administrator (Information Technology)");
        listOccupations.add("Janitorial Supervisors");
        listOccupations.add("Job Analyst");
        listOccupations.add("Job Development Specialist");
        listOccupations.add("Job Printer (Graphic Arts)");
        listOccupations.add("Kindergarten Teacher");
        listOccupations.add("Labor Relations Advisor");
        listOccupations.add("Laboratory Tester	Land Surveyor");
        listOccupations.add("Landscape Architect");
        listOccupations.add("Landscape Contractor");
        listOccupations.add("Lathe Operator");
        listOccupations.add("Law Clerks");
        listOccupations.add("Law Professor");
        listOccupations.add("Legal Assistant");
        listOccupations.add("Legal Secretary");
        listOccupations.add("Legislative Assistant");
        listOccupations.add("Library Assistant");
        listOccupations.add("Library Consultant");
        listOccupations.add("Library Science Professor");
        listOccupations.add("Library Technician");
        listOccupations.add("License Clerk");
        listOccupations.add("Licensed Practical Nurse (LPN)");
        listOccupations.add("Livestock Commission Agent");
        listOccupations.add("Loan Counselor");
        listOccupations.add("Loan Interviewers and Clerks");
        listOccupations.add("Loan Officer");
        listOccupations.add("Locomotive Engineers");
        listOccupations.add("Log Graders and Scalers");
        listOccupations.add("Logging Tractor Operator");
        listOccupations.add("Logging Worker Supervisor");
        listOccupations.add("Machine Feeders and Offbearers");
        listOccupations.add("Mail Clerk");
        listOccupations.add("Mail Machine Operators");
        listOccupations.add("Maintenance Supervisor");
        listOccupations.add("Makeup Artists - Theatrical");
        listOccupations.add("Management Consultant (Analyst)");
        listOccupations.add("Manicurists and Pedicurists");
        listOccupations.add("Manual Arts Therapist");
        listOccupations.add("Mapping Technician");
        listOccupations.add("Marina Boat Charter Administrator");
        listOccupations.add("Marine and Aquatic Biologist");
        listOccupations.add("Marine Architect");
        listOccupations.add("Marine Cargo Surveyor");
        listOccupations.add("Marine Drafter");
        listOccupations.add("Marine Engineer");
        listOccupations.add("Marine Surveyor");
        listOccupations.add("Marine/Port Engineer");
        listOccupations.add("Market Research Analyst");
        listOccupations.add("Marketing Managers");
        listOccupations.add("Marking Clerk");
        listOccupations.add("Marriage and Family Therapists");
        listOccupations.add("Massage Therapist");
        listOccupations.add("Materials Engineer");
        listOccupations.add("Materials Inspector");
        listOccupations.add("Materials Scientist");
        listOccupations.add("Math Professor");
        listOccupations.add("Mathematical Technician");
        listOccupations.add("Meat Packers");
        listOccupations.add("Meat, Poultry, and Fish Trimmers");
        listOccupations.add("Mechanical Drafter");
        listOccupations.add("Mechanical Engineer");
        listOccupations.add("Mechanical Engineering Technician");
        listOccupations.add("Mechanical Inspector");
        listOccupations.add("Medical Administrative Assistant");
        listOccupations.add("Medical and Public Health Social Workers");
        listOccupations.add("Medical and Scientific Illustrator");
        listOccupations.add("Medical Appliance Technician");
        listOccupations.add("Medical Assistant");
        listOccupations.add("Medical Equipment Preparer");
        listOccupations.add("Medical Examiner/Coroner");
        listOccupations.add("Medical Insurance Claims Analyst");
        listOccupations.add("Medical Laboratory Technician");
        listOccupations.add("Medical Photographer");
        listOccupations.add("Medical Records Administrator");
        listOccupations.add("Medical Records Technician");
        listOccupations.add("Medical Secretary");
        listOccupations.add("Medical Technologist");
        listOccupations.add("Medical Transcriptionist");
        listOccupations.add("Mental Health Counselor");
        listOccupations.add("Mentally Retarded Students Teacher");
        listOccupations.add("Merchandise Displayer");
        listOccupations.add("Metal Casting Machine Operator");
        listOccupations.add("Metal Fabricator");
        listOccupations.add("Meter Mechanic");
        listOccupations.add("Middle School Administrator");
        listOccupations.add("Middle School Guidance Counselor");
        listOccupations.add("Middle School Teacher");
        listOccupations.add("Military Analyst");
        listOccupations.add("Military Officer");
        listOccupations.add("Military-Enlisted Personnel");
        listOccupations.add("Mill Worker");
        listOccupations.add("Mine Cutting Machine Operator");
        listOccupations.add("Mine Inspector");
        listOccupations.add("Mining Engineer");
        listOccupations.add("Mining Machine Operator");
        listOccupations.add("Mining Shovel Machine Operator");
        listOccupations.add("Missing Person Investigator");
        listOccupations.add("Missionary Worker (Foreign Country)");
        listOccupations.add("Model Maker");
        listOccupations.add("Model Makers, Metal and Plastic");
        listOccupations.add("Motion Picture Director");
        listOccupations.add("Motion Picture Projectionist");
        listOccupations.add("Motor Vehicle Inspector");
        listOccupations.add("Motorboat Mechanic");
        listOccupations.add("Motorcycle Mechanic");
        listOccupations.add("Municipal Fire Fighting Supervisor");
        listOccupations.add("Museum Curator");
        listOccupations.add("Museum Technicians and Conservators");
        listOccupations.add("Music Arrangers and Orchestrators");
        listOccupations.add("Music Director");
        listOccupations.add("Music Teacher");
        listOccupations.add("Music Therapist");
        listOccupations.add("Musical Instrument Tuner");
        listOccupations.add("Narcotics Investigator (Government)");
        listOccupations.add("New Accounts Clerk (Banking)");
        listOccupations.add("Newspaper Editor");
        listOccupations.add("Newspaper/Magazines Writer");
        listOccupations.add("Non-Retail Sales Supervisor");
        listOccupations.add("Nuclear Engineer");
        listOccupations.add("Nuclear Equipment Operation Technician");
        listOccupations.add("Nuclear Fuels Research Engineer");
        listOccupations.add("Nuclear Medicine Technologist");
        listOccupations.add("Nuclear Monitoring Technician");
        listOccupations.add("Nuclear Power Reactor Operator");
        listOccupations.add("Nuclear Technicians");
        listOccupations.add("Numerical Tool Programmer");
        listOccupations.add("Nurse Practitioner");
        listOccupations.add("Nurse's Aide");
        listOccupations.add("Nursery Workers");
        listOccupations.add("Nursing Professor");
        listOccupations.add("Obstetrician (MD)");
        listOccupations.add("Occupational Analyst");
        listOccupations.add("Occupational Physician (MD)");
        listOccupations.add("Occupational Safety & Health Inspector");
        listOccupations.add("Occupational Therapist");
        listOccupations.add("Occupational Therapy Assistant");
        listOccupations.add("Oceanographic Assistant");
        listOccupations.add("Office Clerk");
        listOccupations.add("Office Machine Mechanic");
        listOccupations.add("Office Supervisor");
        listOccupations.add("Offset Press Operators");
        listOccupations.add("Operating Engineers");
        listOccupations.add("Operations Management Analyst");
        listOccupations.add("Ophthalmic Laboratory Technician");
        listOccupations.add("Ophthalmologist (MD)");
        listOccupations.add("Oral and Maxillofacial Surgeons");
        listOccupations.add("Order Clerk");
        listOccupations.add("Order Fillers, Wholesale and Retail Sales");
        listOccupations.add("Ordinary Seamen");
        listOccupations.add("Ornamental-Metalwork Designer");
        listOccupations.add("Orthodontic Assistant");
        listOccupations.add("Orthodontic Laboratory Technician");
        listOccupations.add("Orthodontist (MD)");
        listOccupations.add("Outdoor Education Teacher");
        listOccupations.add("Overhead Door Installer");
        listOccupations.add("Package Designer");
        listOccupations.add("Packaging Machine Operator");
        listOccupations.add("Packers and Packagers, Hand");
        listOccupations.add("Painter (Industrial)");
        listOccupations.add("Painters, Construction and Maintenance");
        listOccupations.add("Painters, Transportation Equipment");
        listOccupations.add("Park Naturalist");
        listOccupations.add("Parking Enforcement Officer");
        listOccupations.add("Parking Lot Attendant");
        listOccupations.add("Parole Officer");
        listOccupations.add("Parts Salesperson");
        listOccupations.add("Paste-Up Worker (Graphic Arts)");
        listOccupations.add("Patent Agent");
        listOccupations.add("Patent Lawyer");
        listOccupations.add("Pathologist (MD)");
        listOccupations.add("Payroll and Timekeeping Clerks");
        listOccupations.add("PBX Installer and Repairer");
        listOccupations.add("Peace Corps Worker (Volunteer)");
        listOccupations.add("Pediatric Dentist");
        listOccupations.add("Pediatrician (MD)");
        listOccupations.add("Personal Service Supervisor");
        listOccupations.add("Personnel Administrator");
        listOccupations.add("Personnel Assistant");
        listOccupations.add("Personnel Recruiter");
        listOccupations.add("Pest Control Workers");
        listOccupations.add("Pesticide Handlers");
        listOccupations.add("Petroleum Engineer");
        listOccupations.add("Petroleum Geologist");
        listOccupations.add("Petroleum Laboratory Assistant");
        listOccupations.add("Petroleum Refinery Operator");
        listOccupations.add("Petroleum Technician");
        listOccupations.add("Pharmacy Aides");
        listOccupations.add("Pharmacy Technician");
        listOccupations.add("Philosophy and Religion Professor");
        listOccupations.add("Photo-Optics Technician");
        listOccupations.add("Photoengravers (Graphic Arts)");
        listOccupations.add("Photogrammetric Engineer");
        listOccupations.add("Photographic Equipment Mechanic");
        listOccupations.add("Photographic Process Workers");
        listOccupations.add("Physical Education Instructor");
        listOccupations.add("Physical Therapist");
        listOccupations.add("Physical Therapist Aides");
        listOccupations.add("Physical Therapy Assistant");
        listOccupations.add("Physician's Assistant (PA)");
        listOccupations.add("Physician's Office Nurse");
        listOccupations.add("Physics Professor");
        listOccupations.add("Pilot (Commercial Airlines)");
        listOccupations.add("Plant Breeder");
        listOccupations.add("Plant Manager (Manufacturing)");
        listOccupations.add("Plasterers and Stucco Masons");
        listOccupations.add("Plastic Surgeon");
        listOccupations.add("Platemakers (Graphic Arts)");
        listOccupations.add("Plumber (Plumbing Contractor)");
        listOccupations.add("Poets and Lyricists");
        listOccupations.add("Police and Detectives Supervisor");
        listOccupations.add("Police Artist");
        listOccupations.add("Police Identification and Records Officers");
        listOccupations.add("Police Officer");
        listOccupations.add("Political Science Professor");
        listOccupations.add("Political Scientist");
        listOccupations.add("Postal Service Clerks");
        listOccupations.add("Postal Service Mail Carriers");
        listOccupations.add("Postal Service Mail Sorter");
        listOccupations.add("Postmasters and Mail Superintendents");
        listOccupations.add("Power Plant Operators");
        listOccupations.add("Power-Line Installer and Mechanic");
        listOccupations.add("Precision Devices Inspectors and Testers");
        listOccupations.add("Preschool Administrator");
        listOccupations.add("Preschool Teacher");
        listOccupations.add("Pressing Machine Operator");
        listOccupations.add("Pressure Vessel Inspectors");
        listOccupations.add("Printing/Graphic Arts Reproduction Technician");
        listOccupations.add("Printmaker (Artist)");
        listOccupations.add("Private Detectives and Investigators");
        listOccupations.add("Private Nurse");
        listOccupations.add("Private Sector Executives");
        listOccupations.add("Probate Lawyer");
        listOccupations.add("Probation Officer");
        listOccupations.add("Procurement Clerks");
        listOccupations.add("Product Planner");
        listOccupations.add("Product Safety Engineer");
        listOccupations.add("Production Planner");
        listOccupations.add("Production, Planning, and Expediting Clerks");
        listOccupations.add("Professional Sports Scout");
        listOccupations.add("Proofreaders and Copy Markers");
        listOccupations.add("Property Accountant");
        listOccupations.add("Property Assessor");
        listOccupations.add("Property Managers");
        listOccupations.add("Props and Lighting Technicians");
        listOccupations.add("Prosthetic Technician");
        listOccupations.add("Psychiatric Aide");
        listOccupations.add("Psychiatric Technician");
        listOccupations.add("Psychiatrist (MD)");
        listOccupations.add("Psychology Professor");
        listOccupations.add("Public Health Service Officer");
        listOccupations.add("Public Relations Manager");
        listOccupations.add("Public Relations Specialist");
        listOccupations.add("Public Transportation Inspector");
        listOccupations.add("Publications Editor");
        listOccupations.add("Purchasing Agent");
        listOccupations.add("Purchasing Manager");
        listOccupations.add("Quality Control Coordinator");
        listOccupations.add("Quality Control Engineer");
        listOccupations.add("Quality Control Inspector");
        listOccupations.add("Quality Control Technician");
        listOccupations.add("Quarry Worker");
        listOccupations.add("Radar and Sonar Technicians");
        listOccupations.add("Radiation Protection Engineer");
        listOccupations.add("Radiation Therapists");
        listOccupations.add("Radio & TV Announcer");
        listOccupations.add("Radio & TV News Commentator");
        listOccupations.add("Radio & TV Newscaster");
        listOccupations.add("Radio & TV Producer");
        listOccupations.add("Radio & TV Program Director");
        listOccupations.add("Radio & TV Sports Announcer");
        listOccupations.add("Radio & TV Station Administrator");
        listOccupations.add("Radio & TV Talk Show Host");
        listOccupations.add("Radio Mechanics");
        listOccupations.add("Radio Operators");
        listOccupations.add("Radiologic Technicians");
        listOccupations.add("Radiologic Technologist");
        listOccupations.add("Radiologist (MD)");
        listOccupations.add("Rail Yard Engineers");
        listOccupations.add("Railroad Conductors and Yardmasters");
        listOccupations.add("Railroad Engineer");
        listOccupations.add("Railroad Inspector");
        listOccupations.add("Range Manager");
        listOccupations.add("Real Estate Appraiser");
        listOccupations.add("Real Estate Assessor");
        listOccupations.add("Real Estate Broker");
        listOccupations.add("Real Estate Lawyer");
        listOccupations.add("Real Estate Sales Agents");
        listOccupations.add("Recreation Leader");
        listOccupations.add("Recreational Protective Service Worker");
        listOccupations.add("Recreational Therapist");
        listOccupations.add("Recreational Vehicle Mechanic");
        listOccupations.add("Referee / Umpire");
        listOccupations.add("Refuse and Recyclable Material Collectors");
        listOccupations.add("Registrar Administrator");
        listOccupations.add("Reliability Engineer");
        listOccupations.add("Religious Institution Education Coordinator");
        listOccupations.add("Reservation Ticket Agent");
        listOccupations.add("Residence Counselor");
        listOccupations.add("Resource Recovery Engineer");
        listOccupations.add("Resource Teacher");
        listOccupations.add("Respiratory Care Technician");
        listOccupations.add("Respiratory Therapist");
        listOccupations.add("Respiratory Therapy Technicians");
        listOccupations.add("Restaurant Food Coordinator");
        listOccupations.add("Restaurant Manager");
        listOccupations.add("Retail Buyer");
        listOccupations.add("Retail Customer Service Representative");
        listOccupations.add("Retail Inventory Control Analyst");
        listOccupations.add("Retail Sales Department Supervisor");
        listOccupations.add("Retail Salespersons");
        listOccupations.add("Retail Store Manager");
        listOccupations.add("Revenue Agent (Government)");
        listOccupations.add("Safety Inspector");
        listOccupations.add("Sales Engineers");
        listOccupations.add("Sales Floor Stock Clerk");
        listOccupations.add("Sales Managers");
        listOccupations.add("Sales Promoter");
        listOccupations.add("Sales Representative (Aircraft)");
        listOccupations.add("Sales Representative (Chemicals & Drugs)");
        listOccupations.add("Sales Representative (Computers)");
        listOccupations.add("Sales Representative (Graphic Arts)");
        listOccupations.add("Sales Representative (Hotel Furnishings)");
        listOccupations.add("Sales Representative (Medical Equipment)");
        listOccupations.add("Sales Representative (Printed Advertising)");
        listOccupations.add("Sales Representative (Radio & TV Time)");
        listOccupations.add("Sales Representative (Telecommunications)");
        listOccupations.add("Sales Representative (Teleconferencing)");
        listOccupations.add("Sales Representative ( Education Programs)");
        listOccupations.add("Sales Representatives (Agricultural Products)");
        listOccupations.add("Sales Representatives (Instruments)");
        listOccupations.add("Sales Representatives (Mechanical Equipment)");
        listOccupations.add("Sales Representitive (Psychological Tests)");
        listOccupations.add("Sanitary Engineer");
        listOccupations.add("Sawing Machine Operator");
        listOccupations.add("Scanner Operators");
        listOccupations.add("School Nurse");
        listOccupations.add("School Plant Consultant");
        listOccupations.add("School Psychologist");
        listOccupations.add("Scientific Linguist");
        listOccupations.add("Scientific Photographer");
        listOccupations.add("Screen Printing Machine Operators");
        listOccupations.add("Screen Writer");
        listOccupations.add("Script Editor");
        listOccupations.add("Securities Broker");
        listOccupations.add("Security and Fire Alarm Systems Installers");
        listOccupations.add("Security Guard");
        listOccupations.add("Self-Enrichment Education Teachers");
        listOccupations.add("Septic Tank and Sewer Servicers");
        listOccupations.add("Service Station Attendants");
        listOccupations.add("Set Designer");
        listOccupations.add("Set Illustrator");
        listOccupations.add("Sewing Machine Operators");
        listOccupations.add("Sheet Metal Workers");
        listOccupations.add("Ship Carpenters and Joiners");
        listOccupations.add("Ship Engineers");
        listOccupations.add("Ship Master");
        listOccupations.add("Ship Mate");
        listOccupations.add("Ship Pilot");
        listOccupations.add("Shipping, Receiving, and Traffic Clerks");
        listOccupations.add("Shoe Machine Operators");
        listOccupations.add("Signal Switch Repairers");
        listOccupations.add("Skin Care Specialists");
        listOccupations.add("Small Engine Mechanics");
        listOccupations.add("Social and Community Service Managers");
        listOccupations.add("Social and Human Service Assistants");
        listOccupations.add("Social Psychologist");
        listOccupations.add("Social Science Research Assistants");
        listOccupations.add("Social Service Volunteer");
        listOccupations.add("Social Welfare Administrator");
        listOccupations.add("Social Work Professor");
        listOccupations.add("Social Worker");
        listOccupations.add("Sociology Professor");
        listOccupations.add("Soil Conservation Technician");
        listOccupations.add("Soil Conservationist");
        listOccupations.add("Soil Engineer");
        listOccupations.add("Soil Scientist");
        listOccupations.add("Solar Energy Systems Designer");
        listOccupations.add("Solid Waste Disposal Administrator");
        listOccupations.add("Sound Engineering Technicians");
        listOccupations.add("Special Education Administrator");
        listOccupations.add("Special Forces");
        listOccupations.add("Special Forces Officers");
        listOccupations.add("Speech Pathologist");
        listOccupations.add("Speech Writer");
        listOccupations.add("Sport Psychologist");
        listOccupations.add("Sport's/Entertainment Agent (Manager)");
        listOccupations.add("Sports Agent");
        listOccupations.add("Sports Events Business Manager");
        listOccupations.add("Sports Physician (Orthopedist)");
        listOccupations.add("Sportswriter (Journalist)");
        listOccupations.add("Stained Glass Artist");
        listOccupations.add("Standards Engineer");
        listOccupations.add("Statement Clerks");
        listOccupations.add("Stationary Engineers");
        listOccupations.add("Statistical Assistants");
        listOccupations.add("Steel Workers");
        listOccupations.add("Storage and Distribution Manager");
        listOccupations.add("Stress Analyst Engineer");
        listOccupations.add("Structural Drafter");
        listOccupations.add("Structural Engineer");
        listOccupations.add("Student Admissions Administrator");
        listOccupations.add("Student Affairs Administrator");
        listOccupations.add("Student Financial Aid Administrator");
        listOccupations.add("Substance Abuse Counselor");
        listOccupations.add("Subway and Streetcar Conductor");
        listOccupations.add("Surgeons (MD)");
        listOccupations.add("Surgical Technician/Technologist");
        listOccupations.add("Survey Researchers");
        listOccupations.add("Surveying Technicians");
        listOccupations.add("Switchboard Operator");
        listOccupations.add("Systems Accountant");
        listOccupations.add("Systems Analyst, Data Processing");
        listOccupations.add("Tax Accountant");
        listOccupations.add("Tax Auditor");
        listOccupations.add("Tax Collector");
        listOccupations.add("Tax Examiner");
        listOccupations.add("Tax Lawyer");
        listOccupations.add("Tax Preparer");
        listOccupations.add("Taxi Drivers and Chauffeurs");
        listOccupations.add("Teacher of the Blind");
        listOccupations.add("Teachers Aide");
        listOccupations.add("Team Assemblers");
        listOccupations.add("Technical & Scientific Publications Editor");
        listOccupations.add("Technical Directors/Managers");
        listOccupations.add("Technical Illustrator");
        listOccupations.add("Technical Publications Writer");
        listOccupations.add("Technological Espionage Intelligence Agent");
        listOccupations.add("Telecommunications Line Installers and Repairers");
        listOccupations.add("Telecommunications Maintenance Worker");
        listOccupations.add("Telecommunications Technician");
        listOccupations.add("Telephone Station Installers");
        listOccupations.add("Textile Bleaching and Dyeing Machine Operators");
        listOccupations.add("Textile Cutting Machine Operators");
        listOccupations.add("Textile Designer");
        listOccupations.add("Tile and Marble Setters");
        listOccupations.add("Title Examiner");
        listOccupations.add("Title Searchers");
        listOccupations.add("Tool & Machine Designer");
        listOccupations.add("Tool and Die Makers");
        listOccupations.add("Tool Grinders, Filers, and Sharpeners");
        listOccupations.add("Tour Guide");
        listOccupations.add("Town Clerk");
        listOccupations.add("Traffic Administrator (Freight & Passenger)");
        listOccupations.add("Traffic Agent");
        listOccupations.add("Traffic Technicians");
        listOccupations.add("Transit and Railroad Police");
        listOccupations.add("Transportation Attendants");
        listOccupations.add("Transportation Systems Design Engineer");
        listOccupations.add("Travel Agent");
        listOccupations.add("Travel Clerks");
        listOccupations.add("Travel Counselor");
        listOccupations.add("Travel Writer (Journalist)");
        listOccupations.add("Treasurer (Corporate)");
        listOccupations.add("Treatment Plant Operators");
        listOccupations.add("Tree Trimmers and Pruners");
        listOccupations.add("Truck Driver, Light Duty");
        listOccupations.add("Truck Driver, Long Distance");
        listOccupations.add("Ultrasound Technologist");
        listOccupations.add("Unemployment Inspector");
        listOccupations.add("Urban and Regional Planner");
        listOccupations.add("Ushers and Lobby Attendants");
        listOccupations.add("Utility Meter Reader");
        listOccupations.add("Vending Machine Mechanic");
        listOccupations.add("Veterinarian (VMD)");
        listOccupations.add("Veterinarian Technician");
        listOccupations.add("Veterinary Assistant");
        listOccupations.add("Video Engineer");
        listOccupations.add("Vocational Education Instructors College");
        listOccupations.add("Vocational Education Teachers, High School");
        listOccupations.add("Vocational Education Teachers, Middle School");
        listOccupations.add("Vocational Rehabilitation Counselor");
        listOccupations.add("Voice Pathologist");
        listOccupations.add("Waiters and Waitresses");
        listOccupations.add("Warehouse Stock Clerk");
        listOccupations.add("Watch Repairers");
        listOccupations.add("Water Pollution Control Inspector");
        listOccupations.add("Weather Observer");
        listOccupations.add("Web Art Director");
        listOccupations.add("Weighers and Measurers");
        listOccupations.add("Welder (Gas, Arc, Plasma, Laser)");
        listOccupations.add("Welfare Eligibility Workers and Interviewers");
        listOccupations.add("Wholesale Buyers");
        listOccupations.add("Wildlife Biologist");
        listOccupations.add("Wildlife Control Agent");
        listOccupations.add("Windows - Draperies Treatment Specialist");
        listOccupations.add("Woodworking Machine Operators");
        listOccupations.add("Word Processing Specialist");
        listOccupations.add("Writer /Author");
        listOccupations.add("Zoo Veterinarian");
        listOccupations.add("Zoologist");
    }
    private static final long serialVersionUID = 1L;
    public static String DEFAULT_USERNAME = "default_user";
    private static Logger log = LoggerFactory.getLogger(Customer.class);
    private long id;
    private String userName;
    private String firstName;
    private String lastName;
    private String middleName;
    private Date dob;
    private String occupation;
    private int rewardPoints;
    private Address address;

    public Customer() {
        super();
    }

    public Customer(long id, String userName, String firstName, String lastName,
                    String middleName, int rewardPoints, Date dob, String occupation,
                    Address address) {
        super();
        this.id = id;
        this.userName = userName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
        this.rewardPoints = rewardPoints;
        this.dob = dob;
        this.occupation = occupation;
        this.address = address;
    }

    public static Customer createRandom(long id, String userName) {
        RandomUtil randomUtil = new RandomUtil(System.nanoTime());

        Customer customer = new Customer();
        customer.setId(id);
        customer.setUserName(((null != userName && !"".equals(userName)) ? userName : DEFAULT_USERNAME) + "-" + id);
        customer.setFirstName(randomUtil.getRandomObjectFromList(listFirstName));
        customer.setLastName(randomUtil.getRandomObjectFromList(listLastName));
        customer.setMiddleName(randomUtil.getRandomObjectFromList(listFirstName));

        int year = randomUtil.generateRandomInt(1950, Calendar.getInstance().get(Calendar.YEAR), true);
        customer.setDob(randomUtil.generateRandomDate(year));
        customer.setOccupation(randomUtil.getRandomObjectFromList(listOccupations));
        customer.setRewardPoints(randomUtil.generateRandomInt(1000000));
        customer.setAddress(Address.createRandom());

        log.debug("Customer created:" + customer.toString());
        return customer;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDob() {
        return dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public int getRewardPoints() {
        return rewardPoints;
    }

    public void setRewardPoints(int rewardPoints) {
        this.rewardPoints = rewardPoints;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", middleName='" + middleName + '\'' +
                ", dob=" + dob +
                ", occupation='" + occupation + '\'' +
                ", rewardPoints=" + rewardPoints +
                ", address=" + address +
                '}';
    }
}